### ISSUE TITLE
Incorrect parsing for named views

### ISSUE THREAD

**Issue by revolter** [johnpatrickmorgan/wtfautolayout#1]
I set the `accessibilityIdentifier` for a `UIView` and the constraint error looks like this (trimmed):

    (
        "<NSLayoutConstraint:0x17468b860 progress background.height == 5   (active, names: progress background:0x1089a5290 )>"
    )

and it crashed with:

    UNEXPECTED INPUT:
    Line 2, Column 46
        "<NSLayoutConstraint:0x17468b860 progress background.height == 5   (active, names: progress background:0x1089a5290 )>"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    EXPECTED:
    ':'
    '.'

**Comment by johnpatrickmorgan** [comment]
Thanks for raising an issue. I should be able to add space as a valid character for identifiers, which will fix this. 
`partialInstanceName`:
https://github.com/johnpatrickmorgan/wtfautolayout/blob/master/Sources/App/Parsing/ConstraintsParser%2BInstances.swift

**Comment by revolter** [comment]
Are the parentheses at the end supported? I'm asking because the example doesn't have any.

**Comment by johnpatrickmorgan** [comment]
Yes, you should find removing the space in the identifier it will work for now (until I make the fix):
```
(
    "<NSLayoutConstraint:0x17468b860 progressbackground.height == 5   (active, names: progressbackground:0x1089a5290 )>"
)
```

**Comment by revolter** [comment]
Also, first! 😂

**Comment by johnpatrickmorgan** [comment]
@revolter Thanks again, this fix has now been deployed. [Example](http://www.wtfautolayout.com/?constraintlog=%0A%0A%22%3CNSLayoutConstraint%3A0x17468b860%20progress%20background%2Eheight%20%3D%3D%205%20%20%20%28active%2C%20names%3A%20progress%20background%3A0x1089a5290%20%29%3E%22%0A%0A).
