### ISSUE TITLE
Text not rendered correctly

### ISSUE THREAD

**Issue by jschmid** [johnpatrickmorgan/wtfautolayout#11]
First, thanks for this awesome tool!

There is a problem of formatting with the `<code>` tag. See:

<img width="656" alt="screenshot 2018-11-01 at 07 47 37" src="https://user-images.githubusercontent.com/574168/47836969-7f04cd00-ddaa-11e8-969d-2e4ef807d4e7.png">

I guess the `translatesAutoresizingMaskIntoConstraints` text should be in another font without the `<code>` tags?

**Comment by johnpatrickmorgan** [comment]
Thanks a lot @jschmid for spotting this and raising an issue. This must have crept in during the Vapor 3 upgrade. A fix has now been deployed.
