### ISSUE TITLE
file name with + sign shows syntax error

### ISSUE THREAD

**Issue by alouanemed** [johnpatrickmorgan/wtfautolayout#16]
When a file name has + sign it shows a syntax error:

```
 
Line 3, Column 68
    "<SnapKit.LayoutConstraint:0x7feb4e8fa260@PViewController+Ext.swift#21 App_Debug.StackView:0x7feb4e8d58b0.leading == UILayoutGuide:0x7feb50d2aa70.leading + 10.0>",
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Expected: '#' in constraint instance.file location
Expected: file location in constraint instance
```

Removing the sign +  fixes the error.

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue, which is specific to the way [SnapKit prints constraint descriptions](https://github.com/SnapKit/SnapKit/blob/15beb5221834e220f099a87beb80cc9d9abb16cf/Source/Debugging.swift#L140-L160). The parsing code has now been improved to allow any character (except `#`) for file names in SnapKit descriptions, which should fix this issue. Thanks again.
