### ISSUE TITLE
www prefix doesn’t work with https

### ISSUE THREAD

**Issue by ZevEisenberg** [johnpatrickmorgan/wtfautolayout#17]
I think @chrisballinger and I have identified an issue with HTTPS and subdomain redirects:

http://wtfautolayout.com ✅ (redirects to www)
http://www.wtfautolayout.com ✅
https://wtfautolayout.com ❌ (hangs)
https://www.wtfautolayout.com ✅

**Comment by johnpatrickmorgan** [comment]
Thanks very much for spotting this, I'll have a look into it.

**Comment by johnpatrickmorgan** [comment]
I think this is a limitation of my current setup, where redirection from `wtfautolayout.com` to `www.wtfautolayout.com` is configured in the DNS provider (Namecheap), and SSL certs are managed via Heroku's Automated Certificate Management.

Heroku documents the issue [here](https://help.heroku.com/XWEIV6FE/redirecting-https), and recommends using `ANAME`/`ALIAS` records for the redirection, but [Namecheap doesn't support such records](https://twitter.com/Namecheap/status/1102457084329816066). I think I'd need to move DNS provider and manage redirection at the app level instead to resolve the issue, but I'm not sure it would be worth the complication.

Perhaps there's another solution though, as I'm not knowledgeable in this area.

**Comment by chrisballinger** [comment]
You can use free tier Cloudflare DNS for CNAME flattening and "Universal SSL": https://support.cloudflare.com/hc/en-us/articles/204144518-SSL-FAQ

**Comment by johnpatrickmorgan** [comment]
@chrisballinger Thanks so much, that looks like a much simpler solution. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johnpatrickmorgan** [comment]
This has now been set up, and https://wtfautolayout.com should now redirect properly (thanks @akramhussein for your help). It's brought a number of other improvements too so thanks for raising this issue.
