### ISSUE TITLE
Permalink fails when code contains ampersand &

### ISSUE THREAD

**Issue by NSExceptional** [johnpatrickmorgan/wtfautolayout#19]
The site doesn't properly escape the ampersands when you click permalink

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue. It seems `urlQueryArgumentAllowed` would be more appropriate [here](https://github.com/johnpatrickmorgan/wtfautolayout/blob/77d58393e1e79742297952b490c9d0d8831a6729/Sources/App/Models/ModelRepresentations/LeafNodes.swift#L17).

**Comment by johnpatrickmorgan** [comment]
Thanks again; a fix has been deployed and the issue should now be resolved.
