### ISSUE TITLE
Multiple permalinks for the same query

### ISSUE THREAD

**Issue by revolter** [johnpatrickmorgan/wtfautolayout#3]
If you parse:

    (
        "<NSLayoutConstraint:0x17468b860 progress background.height == 5   (active, names: progress background:0x1089a5290 )>"
    )

and click "Permalink", it gives you this URL:

https://www.wtfautolayout.com/?constraintlog=%0A%0A%22%3CNSLayoutConstraint%3A0x17468b860%20progress%20background%2Eheight%20%3D%3D%205%20%20%20%28active%2C%20names%3A%20progress%20background%3A0x1089a5290%20%29%3E%22%0A%0A

and if you click "Permalink" again, it gives you this URL:

https://www.wtfautolayout.com/?constraintlog=%22%3CNSLayoutConstraint%3A0x17468b860%20progress%20background%2Eheight%20%3D%3D%205%20%20%20%28active%2C%20names%3A%20progress%20background%3A0x1089a5290%20%29%3E%22

It should either hide the button if the `constraintlog` parameter exists, either return the same value everytime for the same query.

**Comment by johnpatrickmorgan** [comment]
@revolter Thanks for picking this up. I have added "\r" and "\r\n" to the characters to be trimmed from the input. I've also ensured the permalink button is not added to a page that has itself been loaded via a permalink - thanks for that suggestion! I will update when the change is deployed.

**Comment by johnpatrickmorgan** [comment]
This has now been deployed.
