### ISSUE TITLE
Unexpected Input error for firstBaseline

### ISSUE THREAD

**Issue by timothycosta** [johnpatrickmorgan/wtfautolayout#4]
The following results in an Unexpected Input error.  Changing "firstBaseline" to "bottom" fixes the issue.

```
(
    "<SnapKit.LayoutConstraint:0x6000002b2660@CCBaseCell.swift#88 NSKVONotifying_LQRoundedCornerView:0x7ff92c7ec1f0.height >= 44.0>",
    "<SnapKit.LayoutConstraint:0x6000004ad800@CCBaseCell.swift#91 UIView:0x7ff92c7ec3c0.height == 1.0>",
    "<SnapKit.LayoutConstraint:0x6000006ae880@CCBaseCell.swift#97 UIView:0x7ff92c7ec560.height == UIView:0x7ff92c7ec3c0.height>",
    "<SnapKit.LayoutConstraint:0x6000006aa0e0@CCBaseCell.swift#100 UIView:0x7ff92c7ec560.centerY == NSKVONotifying_LQRoundedCornerView:0x7ff92c7ec1f0.bottom>",
    "<SnapKit.LayoutConstraint:0x6080006ad4a0@CCTargetCells.swift#43 UIView:0x7ff92e29e6f0.top == NSKVONotifying_LQRoundedCornerView:0x7ff92c7ec1f0.top>",
    "<SnapKit.LayoutConstraint:0x6080004a6e40@CCTargetCells.swift#44 UIView:0x7ff92e29e6f0.bottom == UIView:0x7ff92c7ec560.bottom>",
    "<SnapKit.LayoutConstraint:0x6080002b2fc0@CCTargetCells.swift#142 UILabel:0x7ff92c74c9e0.top == UIView:0x7ff92e29e6f0.topMargin>",
    "<SnapKit.LayoutConstraint:0x6080008a2a60@CCTargetCells.swift#143 UILabel:0x7ff92c74c9e0.firstBaseline == UIView:0x7ff92e29e6f0.bottomMargin>"
)
```

```
UNEXPECTED INPUT:
Line 9, Column 94
    "<SnapKit.LayoutConstraint:0x6080008a2a60@CCTargetCells.swift#143 UILabel:0x7ff92c74c9e0.firstBaseline == UIView:0x7ff92e29e6f0.bottomMargin>"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
EXPECTED:
'm' in minX
't' in trailing
'l' in leading
'h' in height
'm' in minY
'm' in maxY
'm' in midY
'm' in midX
'r' in right
'm' in maxX
'b' in bottomMargin
attribute in dot attribute
't' in trailingMargin
'l' in leadingMargin
'b' in bottom
'c' in centerX
'l' in left
'b' in baseline
'w' in width
't' in top
't' in topMargin
'c' in centerY
```

Brilliant project!  Thanks so much for creating this!

**Comment by johnpatrickmorgan** [comment]
@timothycosta Thanks very much for raising this issue. It looks like I need to add support for 4 attributes:`firstBaseline`, `lastBaseline`, `centerXWithinMargins` and `centerYWithinMargins `. I'll update this issue once its done.

**Comment by johnpatrickmorgan** [comment]
@timothycosta This fix has now been deployed and your input [now parses correctly](http://www.wtfautolayout.com/?constraintlog=%22%3CSnapKit%2ELayoutConstraint%3A0x6000002b2660%40CCBaseCell%2Eswift%2388%20NSKVONotifying%5FLQRoundedCornerView%3A0x7ff92c7ec1f0%2Eheight%20%3E%3D%2044%2E0%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x6000004ad800%40CCBaseCell%2Eswift%2391%20UIView%3A0x7ff92c7ec3c0%2Eheight%20%3D%3D%201%2E0%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x6000006ae880%40CCBaseCell%2Eswift%2397%20UIView%3A0x7ff92c7ec560%2Eheight%20%3D%3D%20UIView%3A0x7ff92c7ec3c0%2Eheight%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x6000006aa0e0%40CCBaseCell%2Eswift%23100%20UIView%3A0x7ff92c7ec560%2EcenterY%20%3D%3D%20NSKVONotifying%5FLQRoundedCornerView%3A0x7ff92c7ec1f0%2Ebottom%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x6080006ad4a0%40CCTargetCells%2Eswift%2343%20UIView%3A0x7ff92e29e6f0%2Etop%20%3D%3D%20NSKVONotifying%5FLQRoundedCornerView%3A0x7ff92c7ec1f0%2Etop%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x6080004a6e40%40CCTargetCells%2Eswift%2344%20UIView%3A0x7ff92e29e6f0%2Ebottom%20%3D%3D%20UIView%3A0x7ff92c7ec560%2Ebottom%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x6080002b2fc0%40CCTargetCells%2Eswift%23142%20UILabel%3A0x7ff92c74c9e0%2Etop%20%3D%3D%20UIView%3A0x7ff92e29e6f0%2EtopMargin%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x6080008a2a60%40CCTargetCells%2Eswift%23143%20UILabel%3A0x7ff92c74c9e0%2EfirstBaseline%20%3D%3D%20UIView%3A0x7ff92e29e6f0%2EbottomMargin%3E%22). Thanks again for raising this issue; I'll now close it.
