### ISSUE TITLE
Support leftMargin

### ISSUE THREAD

**Issue by timothycosta** [johnpatrickmorgan/wtfautolayout#5]
Thanks a ton for fixing that issue yesterday!  It seems `leftMargin` and `rightMargin` are also not supported yet (though I should probably remove those from my own code...):

```
(
    "<NSLayoutConstraint:0x170490e00 UIScrollView:0x1241d1200.left == LingQ.LQScrollingStackView:0x123ed1070.left>",
    "<NSLayoutConstraint:0x170490ea0 UIScrollView:0x1241d1200.right == LingQ.LQScrollingStackView:0x123ed1070.right>",
    "<SnapKit.LayoutConstraint:0x1706b8600@LLAchievementsCells.swift#222 LingQ.LQScrollingStackView:0x123ed1070.left == NSKVONotifying_LQRoundedCornerView:0x123d8da90.leftMargin>",
    "<SnapKit.LayoutConstraint:0x1706b86c0@LLAchievementsCells.swift#222 LingQ.LQScrollingStackView:0x123ed1070.right == NSKVONotifying_LQRoundedCornerView:0x123d8da90.rightMargin>",
    "<SnapKit.LayoutConstraint:0x1706b9260@LLAchievementsCells.swift#203 UIImageView:0x123d8e1f0.width == NSKVONotifying_LQRoundedCornerView:0x123d8da90.width * 0.25>",
    "<NSLayoutConstraint:0x1742812c0 LingQ.LLBadgeView:0x123d8e020.trailing == _UILayoutSpacer:0x1743a0620.trailing>",
    "<NSLayoutConstraint:0x174281450 LingQ.LLBadgeView:0x123d8e020.centerX == UIImageView:0x123d8e1f0.centerX>",
    "<NSLayoutConstraint:0x1704918f0 LingQ.LLBadgeView:0x123d8e020.width == 0>",
    "<NSLayoutConstraint:0x174281400 _UILayoutSpacer:0x1743a0620.trailing >= UIImageView:0x123d8e1f0.trailing>"
)
```

```
UNEXPECTED INPUT:
Line 4, Column 172
    "<SnapKit.LayoutConstraint:0x1706b8600@LLAchievementsCells.swift#222 LingQ.LQScrollingStackView:0x123ed1070.left == NSKVONotifying_LQRoundedCornerView:0x123d8da90.leftMargin>",
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
EXPECTED:
whitespace
digit or whitespace in number
'*' in *
'+' in +
whitespace or '(' in info
'>' in >"
'-' in -
```

**Comment by johnpatrickmorgan** [comment]
@timothycosta Thanks for picking this up too! I've now added support for `leftMargin`, `rightMargin` and some other margined attribute names. Your input should now [parse correctly](http://www.wtfautolayout.com/?constraintlog=%22%3CNSLayoutConstraint%3A0x170490e00%20UIScrollView%3A0x1241d1200%2Eleft%20%3D%3D%20LingQ%2ELQScrollingStackView%3A0x123ed1070%2Eleft%3E%22%2C%0A%22%3CNSLayoutConstraint%3A0x170490ea0%20UIScrollView%3A0x1241d1200%2Eright%20%3D%3D%20LingQ%2ELQScrollingStackView%3A0x123ed1070%2Eright%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x1706b8600%40LLAchievementsCells%2Eswift%23222%20LingQ%2ELQScrollingStackView%3A0x123ed1070%2Eleft%20%3D%3D%20NSKVONotifying%5FLQRoundedCornerView%3A0x123d8da90%2EleftMargin%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x1706b86c0%40LLAchievementsCells%2Eswift%23222%20LingQ%2ELQScrollingStackView%3A0x123ed1070%2Eright%20%3D%3D%20NSKVONotifying%5FLQRoundedCornerView%3A0x123d8da90%2ErightMargin%3E%22%2C%0A%22%3CSnapKit%2ELayoutConstraint%3A0x1706b9260%40LLAchievementsCells%2Eswift%23203%20UIImageView%3A0x123d8e1f0%2Ewidth%20%3D%3D%20NSKVONotifying%5FLQRoundedCornerView%3A0x123d8da90%2Ewidth%20%2A%200%2E25%3E%22%2C%0A%22%3CNSLayoutConstraint%3A0x1742812c0%20LingQ%2ELLBadgeView%3A0x123d8e020%2Etrailing%20%3D%3D%20%5FUILayoutSpacer%3A0x1743a0620%2Etrailing%3E%22%2C%0A%22%3CNSLayoutConstraint%3A0x174281450%20LingQ%2ELLBadgeView%3A0x123d8e020%2EcenterX%20%3D%3D%20UIImageView%3A0x123d8e1f0%2EcenterX%3E%22%2C%0A%22%3CNSLayoutConstraint%3A0x1704918f0%20LingQ%2ELLBadgeView%3A0x123d8e020%2Ewidth%20%3D%3D%200%3E%22%2C%0A%22%3CNSLayoutConstraint%3A0x174281400%20%5FUILayoutSpacer%3A0x1743a0620%2Etrailing%20%3E%3D%20UIImageView%3A0x123d8e1f0%2Etrailing%3E%22). 👍
